# Explorando las formaciones frente a errores en la percepción
## A partir de "Maneuvering and robustness issues in undirecter displacemente-consensus-based formation control" de Héctor García de Marina
En el artículo se modelan los errores en la percepción como un error de escalado y una matriz de rotación que representan un alineado incorrecto en la medida de las posiciones.
$$ (p_i-p_j)_{measurement}=aR(p_i-p_j)$$
$$ a \in \mathcal{R}, R \in \mathcal{SO}(m)$$


## Reproduciendo los resultados del artículo

### Carga de módulos necesarios

In [1]:
import RobotModels as rob
import numpy as np
import matplotlib.pyplot as plt
import graph_utils as graf
import time
from matplotlib import animation
from matplotlib.animation import FuncAnimation
from matplotlib.animation import PillowWriter
import robot_plot_utils as rpu

### Formación inicial con 9 agentes
Generación de las posiciones iniciales y el grafo.
Generación de los factores de escala y matriz de rotación responsable de los errores de alineación

In [2]:
#Posiciones iniciales
pi=np.array([[-10,-10],[-10,0],[-10 ,10],[0,10],[0,0],[0,-10],[10,-10],[10,0],[10,10]])
p=np.zeros([2,9])
numnodos,m=np.shape(pi)
#Formacion
zstar=np.array([-5,-5])
#Grafo
Z=np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[5,8],[8,7],[8,9]])
numarcos,m=np.shape(Z)
# Scale factors
var=0.5
a = 1+2*var*np.random.rand(1,9)-var*np.ones([1,9])
#a=np.ones([1,9])
print(a)
#Misalignments in radians
rm=10*np.pi/180
#rm=0
r=np.zeros([1,9])
r=2*rm*np.random.rand(1,9)-rm*np.ones([1,9])
print(r)
n,m= np.shape(pi)
for i in range(n):
    plt.plot(pi[i,0],pi[i,1],'o')

rpu.dibuja_grafo_2D(pi,Z)

[[0.85117493 0.83191548 0.66670922 0.86704592 1.2166888  1.00912929
  0.88244789 1.15156214 0.88436812]]
[[-0.17318565 -0.15363403 -0.06762477  0.15291384  0.03936455  0.14927597
   0.02351247  0.11962747 -0.16550342]]


### Construcción de las matrices
Construimos la matriz Dx $D_x=D_a \otimes I_m \dot D_R$

In [3]:
m,n=np.shape(a)
Da=np.diag(a[0,:])
#print(Da)
j=0
k=0
DR=np.zeros([n*2,2*n])
for i in range(0,2*n,2):
    DR[j,i]=np.cos(r[0,k])
    DR[j,i+1]=-np.sin(r[0,k])
    DR[j+1,i]=np.sin(r[0,k])
    DR[j+1,i+1]=np.cos(r[0,k])
    j+=2
    k+=1
Im=np.eye(2)
Da_bar=np.kron(Da,Im)
i=n*4
#print(np.shape(DR))
#print(Dr)
Dx=np.dot(Da_bar,DR)
#print(np.shape(Dx))
pesos=np.ones([numnodos,numnodos])
L=graf.matriz_laplaciana(Z,pesos,numnodos,numarcos)
print("L: ")
print(L)
Lbar=np.kron(L,Im)
M=-np.dot(Dx,Lbar)

L: 
[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  3. -1.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  3. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  1.]]


### Ejecución del ejemplo

In [4]:
p=np.zeros([2*n,1])
#print(np.shape(p))
rm=20
pstar=graf.stack(pi)
t=0
tf=100
dt=0.01
nptos=(int)((tf-t)/dt)
print(nptos)
fig2 =plt.figure()
p=2*rm*np.random.rand(2*n)-rm*np.ones(2*n)
posiciones=np.zeros([2*n , nptos])
k=0
Lps=np.dot(Lbar,pstar)
#print(Lps)
#Revisar: Los 5 primeros salen bien pero el resto no
for k in range(nptos):
    pdot=np.dot(M,p)+Lps
    for i in range(0,2*n,2):
        xdot,ydot,thetadot=rob.integrator_point_model(pdot[i],pdot[i+1])
        p[i]+=dt*xdot
        p[i+1]+=dt*ydot
    posiciones[:,k]=p[:]
    t+=dt
print(posiciones[:,k])
colors_f=['bo','go','ro','co','yo','mo','ko','bo','go']
colors_i=['bx','gx','rx','cx','yx','mx','kx','bx','gx']
colors_l=['b','g','r','c','y','m','k','b:','g:']
Z=np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[5,8],[8,7],[8,9]])
j=0
for i in range(n):
    plt.plot(posiciones[j,0],posiciones[j+1,0],colors_i[i])
    plt.plot(posiciones[j,nptos-1],posiciones[j+1,nptos-1],colors_f[i])
    plt.plot(posiciones[j,:],posiciones[j+1,:],colors_l[i])
    j=j+2
#rpu.dibuja_grafo_2D(pi,Z)
pfs=np.zeros([2*n,1])
pfs[:,0]=posiciones[:,nptos-1]
pinis=np.zeros([2*n,1])
pinis[:,0]=posiciones[:,0]
#print(pfs)
pf=graf.unstack(pfs,2)
pini=graf.unstack(pinis,2)
#print(pf)
rpu.dibuja_grafo_2D(pf,Z)
rpu.dibuja_grafo_2D(pini,Z)
plt.show()

10000
[-37.82527442   0.66859277 -40.34245181  12.32485458 -43.36193485
  24.07643222 -31.01736443  22.0491216  -32.2602711   10.61235866
 -33.36223579   0.6145038  -24.32925342  -2.52104877 -24.51312785
   8.97983473 -25.90248282  20.04878207]


### Bias
Voy a sustituir el parámetro de escala y la matriz de rotación por un bias 
$$(p_i-p_j)_{measurement}=(p_i-p_j-b_{ij})$$
Los bias se pueden agrupar en una matriz que no tiene por qué ser simétrica
$$B \in \mathcal{R}^{nxn}$$
siendo n el número de agentes
1. Voy a generar una matriz aleatoria $B_1 \in \mathcal{R}^{nxn}$ con elementos $b_{ij}=0$
2.  Asigno un valor aleatorio entre $[0,1]$ a los elementos conectados $ b_{ij}\neq 0$ si $\exists \hspace{1cm} Z(p)=(i,j) \hspace{1cm} \text{or} \hspace{1cm} Z(p)=(j,i)$

In [5]:
#Z=np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[5,8],[8,7],[8,9]])
b=np.zeros([numnodos,numnodos])
for k in range(numarcos):
    i=Z[k,0]
    j=Z[k,1]
    b[i-1,j-1]=np.random.rand(1,1)
    b[j-1,i-1]=np.random.rand(1,1)
print(b)
    

[[0.         0.81599285 0.         0.         0.         0.
  0.         0.         0.        ]
 [0.45031551 0.         0.37040779 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.3474844  0.         0.9121912  0.         0.
  0.         0.         0.        ]
 [0.         0.         0.56372264 0.         0.70327053 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.51681881 0.         0.98682086
  0.         0.39523239 0.        ]
 [0.         0.         0.         0.         0.77172821 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.13503106 0.        ]
 [0.         0.         0.         0.         0.0382247  0.
  0.51987782 0.         0.73180817]
 [0.         0.         0.         0.         0.         0.
  0.         0.43464375 0.        ]]


/tmp/ipykernel_44254/3840394568.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  b[i-1,j-1]=np.random.rand(1,1)
/tmp/ipykernel_44254/3840394568.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  b[j-1,i-1]=np.random.rand(1,1)


Pruebo a ejecutar a ver el efecto

In [6]:
p=np.zeros([2*n,1])
#print(np.shape(p))
rm=20
pstar=graf.stack(pi)
t=0
tf=100
dt=0.01
nptos=(int)((tf-t)/dt)
print(nptos)
fig2 =plt.figure()
p=2*rm*np.random.rand(2*n)-rm*np.ones(2*n)
posiciones=np.zeros([2*n , nptos])
k=0
Lps=np.dot(Lbar,pstar)

for k in range(nptos):
    pdot=np.dot(M,p)+Lps
    for i in range(0,2*n,2):
        xdot,ydot,thetadot=rob.integrator_point_model(pdot[i],pdot[i+1])
        p[i]+=dt*xdot
        p[i+1]+=dt*ydot
    posiciones[:,k]=p[:]
    t+=dt
print(posiciones[:,k])
colors_f=['bo','go','ro','co','yo','mo','ko','bo','go']
colors_i=['bx','gx','rx','cx','yx','mx','kx','bx','gx']
colors_l=['b','g','r','c','y','m','k','b:','g:']
Z=np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[5,8],[8,7],[8,9]])
j=0
for i in range(n):
    plt.plot(posiciones[j,0],posiciones[j+1,0],colors_i[i])
    plt.plot(posiciones[j,nptos-1],posiciones[j+1,nptos-1],colors_f[i])
    plt.plot(posiciones[j,:],posiciones[j+1,:],colors_l[i])
    j=j+2
#rpu.dibuja_grafo_2D(pi,Z)
pfs=np.zeros([2*n,1])
pfs[:,0]=posiciones[:,nptos-1]
pinis=np.zeros([2*n,1])
pinis[:,0]=posiciones[:,0]
#print(pfs)
pf=graf.unstack(pfs,2)
pini=graf.unstack(pinis,2)
#print(pf)
rpu.dibuja_grafo_2D(pf,Z)
rpu.dibuja_grafo_2D(pini,Z)
plt.show()

10000
[-45.37791933   3.36377774 -47.89509775  15.02004031 -50.91458265
  26.77161937 -38.57001467  24.74431079 -39.81292382  13.30755004
 -40.91488878   3.30969549 -31.8819088    0.17414497 -32.06578252
  11.67502779 -33.45513834  22.74397563]
